### ISSUE TITLE
Autoload Modules on application config file

### ISSUE THREAD

**Issue by 814ckc0d3** [814ckc0d3/zf2#1]
Hi, Agustin I suppose that this autoload method exists on ZF2 so I have to study it after the cert exam, but at the moment i need if it is possible to ask you about the config files.
I want to implement the modules dynamically, is done (not a good base code and i have to make it better but i want to access to the module config array to seek for a variable called 'active' to include the module when the value is set to true. the question is; when i execute get_declared_classes to take a look to the current classes in use, i don´t understand exactly how to access to the config vars (Zend/Mvc/Application or Classloader...) its driving me crazy
Thanks for whatever you help me

**Comment by agustincl** [comment]
Well, we need to talk about the "dynamically loaded modules". This is not a good idea. Maybe you need to investigate more on ACL (access control list). A good scenario is an application with all its modules, an authenticated user, and a role for that user. Depending of the users role, you grant access to the desires modules. 

But, to answer your question, you need to check the config file and the "options" to read the variables in the config and use its as properties of a class. 
You can check it here, in an example module I wrote named breaker: 
There are three files in the process: 
1. The ModuleOptions.php
   https://github.com/agustincl/cursoZf2/blob/master/module/Breaker/src/Breaker/Options/ModuleOptions.php
2. The global module configuration file
   https://github.com/agustincl/cursoZf2/blob/master/config/autoload/breaker.global.php
3. And the Module.php (in the modules folder)
   https://github.com/agustincl/cursoZf2/blob/master/module/Breaker/Module.php

The idea is you inject the "global config (2)" into the "options class(3)" in the "module(1)" file.

Just take a look of these files and don't hesitate to ask anything, I'm glad to help.

Acl.

**Comment by 814ckc0d3** [comment]
Thank you very much, this breaker class may help me for the moment, i take a look to the auth classes and i will implement then in a short time, I hope. i will ask u for more help when needed, thanks again
